name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
      - 'renovate/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '21.x', '22.x', '23.x']

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13  
      - name: Build and test the project
        run: |
          rm -rf smarthome_dwh.duckdb
          source venv/bin/activate && duckdb smarthome_dwh.duckdb < scripts/duckdb_load.sql
          source venv/bin/activate && dbt run
          source venv/bin/activate && dbt test
        