name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
      - 'renovate/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13  
      - name: Install Python dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate && pip install -r requirements.txt
      - name: Set up DuckDB CLI
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip && unzip duckdb_cli-linux-amd64.zip
      - name: Install dbt dependencies
        run: |
          source venv/bin/activate && dbt deps
      - name: Load data into DuckDB
        run: |
          source venv/bin/activate && ./duckdb smarthome_dwh.duckdb < scripts/duckdb_load.sql
      - name: Build dbt
        run: |
          source venv/bin/activate && dbt build && dbt docs generate
      - name: Install Evidence
        run: npm run evidence:install
      - name: Source data to Evidence
        run: npm run evidence:sources
      - name: Test Evidence
        run: npm run evidence:test
  